/* Canonical word themes shared by Anitas Word Path and Anitas Word Cube.
   Edit theme words here so both game types always stay in sync. */
(() => {
  const themes = [{"name":"Animals","words":["CHIMPANZEE","BUTTERFLY","CROCODILE","ALLIGATOR","ELEPHANT","DOLPHIN","PANTHER","RABBIT","MONKEY","TURTLE","PARROT","JAGUAR","HORSE","WHALE","TIGER","ZEBRA","PANDA","OTTER","KOALA","SHEEP","MOOSE","BEAVER","BADGER","FALCON","EAGLE","WOLF","BEAR","LION","SWAN","DUCK","FROG","FOX","EMU","ANT","OWL","APE","CAT","DOG","CAMEL","GORILLA","CHEETAH","LEOPARD","HAMSTER","PENGUIN","BUFFALO","DONKEY","GECKO","IGUANA","MANTIS","COBRA","SLOTH","RHINOCEROS","ORANGUTAN","HIPPOPOTAMUS"]},{"name":"Ocean","words":["JELLYFISH","SEAHORSE","STARFISH","OCTOPUS","DOLPHIN","TURTLE","MARLIN","SALMON","ANCHOR","LAGOON","CORAL","SHARK","WHALE","MANTA","OCEAN","PEARL","SHELL","COAST","REEF","SQUID","WAVES","TIDES","CRAB","SEAL","KELP","SURF","BOAT","WAVE","TIDE","SEA","FIN","EEL","COD","HARBOR","ISLAND","LOBSTER","SEAGULL","CURRENT","SEABED","PLANKTON","BARNACLE","SEASHELL","ANCHOVY","SARDINE","BUBBLES","SAILBOAT","BEACH","CLIFF","COVE","BAY","HAMMERHEAD","BIOLUMINESCENCE","UNDERWATER"]},{"name":"Food","words":["STRAWBERRY","CHOCOLATE","PINEAPPLE","BLUEBERRY","SANDWICH","SPAGHETTI","PANCAKE","BANANA","ORANGE","CARROT","CHEESE","TOMATO","COOKIE","YOGURT","MUFFIN","BREAD","GRAPE","HONEY","LEMON","MELON","PEACH","APPLE","MANGO","OLIVE","CREAM","TOAST","SALAD","BERRY","SUGAR","RICE","FIG","PIE","EGG","HAM","POTATO","AVOCADO","BURGER","NOODLES","WAFFLE","BISCUIT","CEREAL","BUTTER","CHERRY","COCONUT","GARLIC","GINGER","PUMPKIN","PEPPER","PASTA","SOUP","CAULIFLOWER","POMEGRANATE","PASSIONFRUIT"]},{"name":"Nature","words":["WATERFALL","MOUNTAIN","RAINFOREST","SUNFLOWER","WOODLAND","MEADOW","FOREST","BREEZE","THUNDER","RAINBOW","RIVER","STONE","CLOUD","PLANT","GRASS","MAPLE","CEDAR","CLIFF","FLAME","FIELD","LEAF","PINE","MOSS","TREE","RAIN","SNOW","WIND","ROCK","OAK","SUN","SKY","FOG","MUD","VALLEY","DESERT","CANYON","GLACIER","JUNGLE","POND","STREAM","FLOWER","BLOSSOM","BRANCH","ROOT","VOLCANO","ISLAND","HILL","SHADOW","EARTH","GARDEN","THUNDERCLOUD","BIODIVERSITY","WILDFLOWERS"]},{"name":"Space","words":["TELESCOPE","ASTEROID","SATELLITE","SPACESHIP","UNIVERSE","GALAXY","NEBULA","METEOR","ROCKET","PLANET","COSMOS","CRATER","ORBIT","SOLAR","SATURN","VENUS","PLUTO","COMET","LUNAR","MOON","MARS","STAR","EARTH","SPACE","SUN","SKY","JUPITER","MERCURY","GRAVITY","ASTRONAUT","MISSION","MODULE","ECLIPSE","ALIEN","ORBITER","COSMIC","PLANETARY","STARDUST","MOONLIGHT","SUPERNOVA","BLACKHOLE","MILKYWAY","LAUNCH","CAPSULE","RADIATION","VACUUM","CONSTELLATION","INTERSTELLAR","GRAVITATION"]},{"name":"Fantasy","words":["ENCHANTMENT","ADVENTURER","DRAGON","WIZARD","KNIGHT","CASTLE","POTION","PRINCESS","SORCERER","TREASURE","MAGIC","SHIELD","GOBLIN","MERLIN","SWORD","CROWN","TOWER","GHOST","GIANT","FAIRY","SPELL","QUEST","RUNE","ELF","ORC","IMP","KINGDOM","DUNGEON","PHOENIX","UNICORN","WARLOCK","CRYSTAL","MYSTIC","ELIXIR","THRONE","ARMOR","SCROLL","CHARM","RIDDLE","PORTAL","MONSTER","HERO","VILLAIN","DRUID","TROLL","OGRE","WAND","NECROMANCER","SHAPESHIFTER","DRAGONRIDER"]},{"name":"Technology","words":["SMARTPHONE","COMPUTER","KEYBOARD","INTERNET","SOFTWARE","HARDWARE","DATABASE","BATTERY","SWITCH","SCREEN","SENSOR","CAMERA","TABLET","SERVER","ROBOT","PHONE","LASER","CABLE","MODEM","RADIO","PIXEL","VIDEO","MOTOR","CHIP","CODE","DATA","USB","APP","NETWORK","PROCESSOR","MEMORY","DISPLAY","WIRELESS","BLUETOOTH","SIGNAL","ROUTER","CIRCUIT","DEVICE","DIGITAL","STORAGE","LAPTOP","MONITOR","PRINTER","BROWSER","SYSTEM","UPLOAD","DOWNLOAD","BUTTON","TOUCH","POWER","MICROPROCESSOR","CYBERSECURITY","SEMICONDUCTOR"]},{"name":"Sports","words":["BASKETBALL","VOLLEYBALL","SWIMMING","FOOTBALL","BASEBALL","MARATHON","CYCLING","TENNIS","HOCKEY","BOXING","RUNNER","TRAINING","MATCH","COACH","SKATE","RUGBY","SCORE","POWER","SPORT","SWING","FIELD","RACE","CLIMB","JUMP","TEAM","GOAL","BALL","RUN","SKI","GYM","SPRINTER","STADIUM","PLAYER","REFEREE","MEDAL","TROPHY","FITNESS","WORKOUT","SURFING","SKATING","DIVING","ROWING","HIKING","BOWLING","SOCCER","GOLF","KAYAK","PADDLE","WEIGHTLIFTING","GYMNASTICS","SKATEBOARDING"]},{"name":"Travel","words":["ADVENTURE","AIRPORT","SUITCASE","PASSPORT","JOURNEY","HOLIDAY","HOTEL","TICKET","FLIGHT","TRAIN","TRAVEL","CAMPING","BACKPACK","MAP","ROAD","CITY","BEACH","MUSEUM","BRIDGE","ISLAND","BORDER","VILLAGE","COUNTRY","RESORT","HOSTEL","CABIN","CRUISE","FERRY","TAXI","BUS","CAR","TRIP","TOUR","GUIDE","CAMERA","LUGGAGE","STATION","PLATFORM","DEPARTURE","ARRIVAL","MOUNTAIN","HARBOR","MARKET","SOUVENIR","TRAIL","ROUTE","VACATION","DESTINATION","SIGHTSEEING","EXPLORATION"]},{"name":"Music","words":["GUITAR","PIANO","DRUMMER","MELODY","RHYTHM","CONCERT","SINGER","CHORUS","MUSIC","VIOLIN","TRUMPET","FLUTE","BANJO","LYRICS","STAGE","SOUND","BEAT","SONG","RADIO","BAND","DANCE","VOICE","RECORD","ALBUM","TUNE","BASS","SOLO","DJ","MIC","ORCHESTRA","KEYBOARD","SPEAKER","HEADPHONES","HARMONY","GROOVE","TEMPO","ARTIST","PLAYLIST","MUSICAL","CELLO","HARP","SAXOPHONE","CLARINET","PERCUSSION","MICROPHONE","SYNTHESIZER","SONGWRITING","CONDUCTOR"]},{"name":"Home","words":["KITCHEN","BEDROOM","BATHROOM","WINDOW","DOORWAY","CARPET","CURTAIN","PILLOW","BLANKET","TABLE","CHAIR","SOFA","LAMP","SHELF","MIRROR","DRAWER","CUPBOARD","GARAGE","GARDEN","FENCE","ROOF","WALL","FLOOR","STAIRS","CLOCK","VASE","CANDLE","BASKET","TOWEL","SHOWER","SINK","OVEN","FRIDGE","FREEZER","PAN","POT","PLATE","SPOON","FORK","KNIFE","MUG","GLASS","KEY","LOCK","BED","DESK","ROOM","DISHWASHER","BOOKSHELF","WARDROBE"]},{"name":"Transport","words":["AIRPLANE","HELICOPTER","MOTORCYCLE","BICYCLE","SCOOTER","SUBWAY","TRAM","TRAIN","TRUCK","CAR","BUS","TAXI","FERRY","BOAT","SHIP","ROCKET","ENGINE","WHEEL","BRAKE","PEDAL","STEERING","STATION","TUNNEL","BRIDGE","ROAD","TRACK","RAIL","DRIVER","PILOT","CAPTAIN","VEHICLE","TRAFFIC","HIGHWAY","GARAGE","PARKING","FUEL","DIESEL","ELECTRIC","MOTOR","TIRE","SIGNAL","CARGO","SEAT","CABIN","LOCOMOTIVE","SPEEDBOAT","AMBULANCE"]},{"name":"Weather","words":["THUNDERSTORM","LIGHTNING","RAINBOW","SUNSHINE","SNOWFLAKE","BLIZZARD","DRIZZLE","TORNADO","HURRICANE","WEATHER","THUNDER","BREEZE","CLOUDY","STORM","RAIN","SNOW","WIND","SUNNY","FROST","MIST","FOG","ICE","HEAT","COLD","WARM","TEMPERATURE","FORECAST","HUMIDITY","CLIMATE","SHOWER","FREEZING","DROUGHT","MONSOON","CYCLONE","GUST","CLOUD","SKY","THUNDERCLOUD","PRECIPITATION","ATMOSPHERE"]},{"name":"School","words":["NOTEBOOK","CLASSROOM","HOMEWORK","TEACHER","STUDENT","PENCIL","ERASER","RULER","LESSON","SCHOOL","BOOK","PAPER","DESK","CHAIR","BOARD","CLASS","TEST","EXAM","GRADE","MATH","SCIENCE","HISTORY","MUSIC","SPORT","LANGUAGE","LIBRARY","BACKPACK","LUNCH","BREAK","FRIEND","QUESTION","ANSWER","PROJECT","COMPUTER","CALCULATOR","DICTIONARY","READING","WRITING","SPELLING","DRAWING","LEARNING","MATHEMATICS","GEOGRAPHY","LABORATORY"]},{"name":"Jobs","words":["ENGINEER","TEACHER","DOCTOR","NURSE","PILOT","CHEF","BAKER","FARMER","DRIVER","ARTIST","DESIGNER","MECHANIC","BUILDER","SCIENTIST","PROGRAMMER","DENTIST","LAWYER","WRITER","ACTOR","SINGER","DANCER","PLUMBER","ELECTRICIAN","CARPENTER","TAILOR","BARBER","CASHIER","MANAGER","POLICE","FIREFIGHTER","REPORTER","PHOTOGRAPHER","ARCHITECT","GARDENER","COACH","VET","VETERINARIAN","PALEONTOLOGIST","ARCHITECTURE"]},{"name":"City","words":["SKYSCRAPER","APARTMENT","BUILDING","STREET","AVENUE","TRAFFIC","CROSSING","STATION","MARKET","MUSEUM","THEATER","HOTEL","RESTAURANT","CAFE","PARK","BRIDGE","TUNNEL","SQUARE","FOUNTAIN","LIBRARY","HOSPITAL","SCHOOL","OFFICE","SHOP","STORE","BANK","PLAZA","SIDEWALK","BUS","TAXI","TRAIN","METRO","LIGHTS","TOWER","CHURCH","CASTLE","HARBOR","RIVER","ROAD","CITY","NEIGHBORHOOD","INTERSECTION","UNDERGROUND"]},{"name":"Tricking","words":["TRICKING","BACKFLIP","FRONTFLIP","SIDEFLIP","CARTWHEEL","AERIAL","WEBSTER","GAINER","CORK","TWIST","KICK","HOOKKICK","ROUNDHOUSE","TORNADO","BUTTERFLY","SWIPE","RAIZ","SCOOT","CHEAT","COMBO","LANDING","TAKEOFF","ROTATION","SPIN","FLIP","KICKS","SETUP","FLOW","POWER","HEIGHT","BALANCE","CONTROL","MOMENTUM","AXIS","TUCK","LAYOUT","STANCE","TRANSITION","POP","SWING","HYPER","FULLTWIST","BACKSIDE","FRONTSIDE","TECHNIQUE","PRECISION","SPEED","STYLE","TRAINING","FLEXIBILITY","DOUBLEBACKFLIP","CORKSCREW","COMBINATION"]},{"name":"Bouldering","words":["BOULDERING","CRIMP","SLOPER","PINCH","JUG","POCKET","UNDERCLING","SIDEPULL","HEELHOOK","TOEHOOK","MANTLE","DYNO","CAMPUS","CHALK","HOLDS","PROBLEM","SEND","FLASH","TOP","MATCH","FLAG","DROPKNEE","SMEAR","VOLUME","WALL","OVERHANG","SLAB","ARETE","CRUX","BETA","BRUSH","MAT","SPOTTER","ROUTE","STATIC","DYNAMIC","LOCKOFF","DEADPOINT","COMPRESSION","HANGBOARD","POWER","TENSION","COORDINATION","COMPETITION","START","FINISH","SEQUENCE","FOOTWORK","FINGERS","GRIP","BODYTENSION","HEELTOEHOOK","ROUTEREADING"]},{"name":"Climbing","words":["CLIMBING","BELAY","HARNESS","CARABINER","QUICKDRAW","ROPE","ANCHOR","LEAD","TOPROPE","CRAG","ROUTE","PITCH","BOLT","CLIP","CHALK","HELMET","SLING","CAM","NUT","PROTECTION","RAPPEL","ABSEIL","ASCENDER","DESCENDER","FOOTWORK","GRIP","EDGE","JAM","CRACK","FACE","CHIMNEY","ARETE","OVERHANG","SLAB","SUMMIT","APPROACH","PARTNER","BELAYER","CLIMBER","EXPOSURE","FALL","SEND","REDPOINT","ONSIGHT","FLASH","PROJECT","CRUX","BETA","REST","LOWER","COUNTERPRESSURE","MULTIPITCH","GEARPLACEMENT"]}];
  window.ANITAS_THEME_POOLS = Object.freeze(themes.map(theme => Object.freeze({
    name: theme.name,
    words: Object.freeze([...theme.words])
  })));
  window.ANITAS_THEME_META = Object.freeze({themeCount:19,wordCount:936});
})();

/* Large-grid path-generation guard.
   9x9 and 12x12 previously used recursive Hamiltonian backtracking that could
   explode combinatorially and lock the browser. The existing generator is
   kept intact, but its neighbour filtering is constrained to a guaranteed
   Hamiltonian cycle for the two large grids. That turns the expensive search
   into a linear-time path walk while leaving 6x6 behaviour unchanged. */
(()=>{
  if(Array.prototype.__anitasLargeGridFilterGuard)return;
  Object.defineProperty(Array.prototype,'__anitasLargeGridFilterGuard',{value:true,configurable:false});

  const originalFilter=Array.prototype.filter;
  const cycles={
    9:[0,1,2,3,4,5,6,7,8,17,16,15,14,13,12,11,10,19,20,21,22,23,24,25,26,35,34,33,32,31,30,29,28,37,38,39,40,41,42,43,44,53,52,51,50,49,48,47,46,55,56,57,58,59,60,61,62,71,80,70,79,78,69,68,77,76,67,66,75,74,65,64,73,72,63,54,45,36,27,18,9],
    12:[0,1,2,3,4,5,6,7,8,9,10,11,23,22,21,20,19,18,17,16,15,14,13,25,26,27,28,29,30,31,32,33,34,35,47,46,45,44,43,42,41,40,39,38,37,49,50,51,52,53,54,55,56,57,58,59,71,70,69,68,67,66,65,64,63,62,61,73,74,75,76,77,78,79,80,81,82,83,95,94,93,92,91,90,89,88,87,86,85,97,98,99,100,101,102,103,104,105,106,107,119,118,117,116,115,114,113,112,111,110,109,121,122,123,124,125,126,127,128,129,130,131,143,142,141,140,139,138,137,136,135,134,133,132,120,108,96,84,72,60,48,36,24,12]
  };

  function selectedGridSize(){
    const selected=document.querySelector('#gridChoices [data-grid].selected');
    return Number(selected?.dataset.grid)||6;
  }

  function neighborSignature(size,idx){
    const r=Math.floor(idx/size),c=idx%size,out=[];
    for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){
      if(!dr&&!dc)continue;
      const rr=r+dr,cc=c+dc;
      if(rr>=0&&rr<size&&cc>=0&&cc<size)out.push(rr*size+cc);
    }
    return out.join(',');
  }

  const signatures={};
  for(const size of [9,12]){
    const map=new Map();
    for(let i=0;i<size*size;i++)map.set(neighborSignature(size,i),i);
    signatures[size]=map;
  }

  let active=null;
  Array.prototype.filter=function(callback,thisArg){
    const result=originalFilter.call(this,callback,thisArg);
    const size=selectedGridSize();
    if(size!==9&&size!==12)return result;
    if(this.length<3||this.length>8||!this.every(Number.isInteger))return result;

    const current=signatures[size].get(this.join(','));
    if(current===undefined)return result;
    const cycle=cycles[size];

    if(!active||active.size!==size||active.expected!==current||active.step>=cycle.length-1){
      const at=cycle.indexOf(current);
      if(at<0)return result;
      active={size,path:cycle.slice(at).concat(cycle.slice(0,at)),step:0,expected:current};
    }

    const next=active.path[active.step+1];
    if(next!==undefined&&result.includes(next)){
      active.step++;
      active.expected=next;
      return [next];
    }

    active=null;
    return result;
  };
})();
