(()=>{'use strict';
const V='0.4.11',R=6,C=6,MS=8000,W=['COFFEE','MUG','STEAM','BEANS','LATTE','WARM'],POOL='EEEEEEEEEEEEAAAAAAAAAIIIIIIIIOOOOOOOONNNNNNRRRRRRTTTTTTLLLLSSSSUUUUDDDDGGGBBCCMMPPFFHHVVWWYYKJXQZ',$=id=>document.getElementById(id),stage=$('stage'),canvas=$('gameCanvas'),ui={word:$('currentWord'),meta:$('selectionMeta'),bar:$('timerBar'),targets:$('targetList'),found:$('foundStat'),score:$('scoreStat'),tiles:$('tileStat'),route:$('routeStat'),time:$('elapsedStat'),clear:$('clearBtn'),check:$('checkBtn'),newBtn:$('newBtn'),reset:$('resetViewBtn'),theme:$('themeBtn'),toast:$('toast'),win:$('win'),winText:$('winText'),next:$('nextBtn'),metaColor:$('themeColorMeta')};
if(!window.THREE)throw Error('Three.js failed to load');
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(30,1,.1,100),renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true,powerPreference:'high-performance'});camera.position.set(0,.04,8.2);renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));if('outputColorSpace'in renderer)renderer.outputColorSpace=THREE.SRGBColorSpace;else renderer.outputEncoding=THREE.sRGBEncoding;renderer.shadowMap.enabled=false;scene.add(new THREE.AmbientLight(0xffffff,1.15),new THREE.HemisphereLight(0xf8fffc,0x9ab5ad,1.1));let dl=new THREE.DirectionalLight(0xffffff,.8);dl.position.set(-3.8,5.2,6.6);scene.add(dl);dl=new THREE.DirectionalLight(0xe5fff7,.45);dl.position.set(4.2,1.8,3.5);scene.add(dl);
const pivot=new THREE.Group(),content=new THREE.Group(),body=new THREE.Group(),tg=new THREE.Group(),lg=new THREE.Group(),trails=new THREE.Group();content.add(body,tg,trails,lg);pivot.add(content);scene.add(pivot);const ray=new THREE.Raycaster(),ptr=new THREE.Vector2();
let dark=false,board=[],targets=[...W],found=new Set(),foundPaths=new Map(),solved=new Set(),sel=[],tiles=[],tileMeshes=[],adj=new Map(),score=0,flash=new Map(),toastTimer=null,rx=-.19,ry=-.28,rot=false,pid=null,lx=0,ly=0,timer=null,timerStart=0,timerRemain=MS,timerPaused=false,startMs=0,finalMs=0,ticker=null;
const COL={light:{body:0xc3dbd3,body2:0xb8d3ca,inner:0x8fb2ab,handle:0xc7ddd6,tile:0xf8fbfa,text:'#38534b',sel:0x55d7b9,sol:0xb9e58f,bad:0xef9f96,under:0xffffff,pathSel:0x55d7b9,pathSol:0x9bd866,rim:0xd8ece6,tileEdge:0x97aea7,coffee:0x4d2f1f,coffeeHi:0x79513a},dark:{body:0x9fb9b2,body2:0x95b0a9,inner:0x76958e,handle:0xa4c2ba,tile:0xf1f5f3,text:'#2c443d',sel:0x65dfc3,sol:0xaee17f,bad:0xef9f96,under:0x08110e,pathSel:0x65dfc3,pathSol:0x9bd866,rim:0xc8dbd5,tileEdge:0x7f978f,coffee:0x4a2c1d,coffeeHi:0x6b4433}},K=()=>dark?COL.dark:COL.light,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=n=>Math.floor(Math.random()*n),shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){let j=rnd(i+1);[a[i],a[j]]=[a[j],a[i]]}return a},cyl=(th,y,r)=>new THREE.Vector3(Math.sin(th)*r,y,Math.cos(th)*r),mugR=y=>1.48+(1.60-1.48)*clamp((y+1.575)/3.15,0,1);
function clear(g){while(g.children.length){let o=g.children.pop();o.traverse?.(x=>{x.geometry?.dispose?.();if(x.material)(Array.isArray(x.material)?x.material:[x.material]).forEach(m=>{m.map?.dispose?.();m.dispose?.()})})}}
function link(a,b){if(a===b)return;adj.get(a).add(b);adj.get(b).add(a)}
function mat(color,rough=.8){return new THREE.MeshStandardMaterial({color,roughness:rough,metalness:.01,side:THREE.DoubleSide})}
function buildBody(){clear(body);let c=K(),m=new THREE.Mesh(new THREE.CylinderGeometry(1.60,1.48,3.15,160,12,true),mat(c.body,.88));body.add(m);m=new THREE.Mesh(new THREE.CylinderGeometry(1.42,1.32,2.92,160,10,true),new THREE.MeshStandardMaterial({color:c.inner,roughness:.72,side:THREE.BackSide}));m.position.y=.02;body.add(m);m=new THREE.Mesh(new THREE.CylinderGeometry(1.315,1.285,.075,120),mat(c.coffee,.54));m.position.y=1.395;body.add(m);m=new THREE.Mesh(new THREE.TorusGeometry(1.18,.025,12,100),mat(c.coffeeHi,.42));m.rotation.x=Math.PI/2;m.position.y=1.432;body.add(m);m=new THREE.Mesh(new THREE.CylinderGeometry(1.48,1.48,.12,120),mat(c.body2,.86));m.position.y=-1.575;body.add(m);m=new THREE.Mesh(new THREE.TorusGeometry(1.515,.11,28,140),mat(c.rim,.42));m.rotation.x=Math.PI/2;m.position.y=1.575;body.add(m);m=new THREE.Mesh(new THREE.TorusGeometry(1.385,.055,20,140),mat(c.inner,.58));m.rotation.x=Math.PI/2;m.position.y=1.515;body.add(m);m=new THREE.Mesh(new THREE.CylinderGeometry(1.50,1.42,.06,140,1,true),mat(c.body2,.74));m.position.y=1.545;body.add(m);m=new THREE.Mesh(new THREE.TorusGeometry(.82,.16,24,120),mat(c.handle,.68));m.position.set(1.54,.02,0);m.scale.y=1.22;body.add(m)}
function letter(ch,p,n,th){let cv=document.createElement('canvas');cv.width=cv.height=256;let x=cv.getContext('2d');x.fillStyle=K().text;x.font='800 138px Georgia,serif';x.textAlign='center';x.textBaseline='middle';x.fillText(ch,128,136);let tex=new THREE.CanvasTexture(cv);if('colorSpace'in tex)tex.colorSpace=THREE.SRGBColorSpace;let m=new THREE.Mesh(new THREE.PlaneGeometry(.43,.43),new THREE.MeshBasicMaterial({map:tex,transparent:true,depthWrite:false,side:THREE.DoubleSide})),u=new THREE.Vector3(Math.cos(th),0,-Math.sin(th)),v=new THREE.Vector3(0,1,0);m.setRotationFromMatrix(new THREE.Matrix4().makeBasis(u,v,n));m.position.copy(p).add(n.clone().multiplyScalar(.016));m.renderOrder=6;return m}
function outline(t0,t1,yt,yb){let a=[];for(let i=0;i<=8;i++){let th=THREE.MathUtils.lerp(t0,t1,i/8),p=cyl(th,yt,mugR(yt)+.018);a.push(p.x,p.y,p.z)}for(let i=1;i<=6;i++){let y=THREE.MathUtils.lerp(yt,yb,i/6),p=cyl(t1,y,mugR(y)+.018);a.push(p.x,p.y,p.z)}for(let i=1;i<=8;i++){let th=THREE.MathUtils.lerp(t1,t0,i/8),p=cyl(th,yb,mugR(yb)+.018);a.push(p.x,p.y,p.z)}for(let i=1;i<6;i++){let y=THREE.MathUtils.lerp(yb,yt,i/6),p=cyl(t0,y,mugR(y)+.018);a.push(p.x,p.y,p.z)}return a}
function makeTile(r,c,id){let a=-.70+c*(1.40/C),b=-.70+(c+1)*(1.40/C),yt=1.06-r*(2.12/R),yb=1.06-(r+1)*(2.12/R),gt=(b-a)*.10,gy=(yt-yb)*.10,t0=a+gt,t1=b-gt,y0=yt-gy,y1=yb+gy,verts=[],idx=[],sx=6,sy=4;for(let y=0;y<=sy;y++){let yy=THREE.MathUtils.lerp(y0,y1,y/sy),rad=mugR(yy)+.014;for(let x=0;x<=sx;x++){let p=cyl(THREE.MathUtils.lerp(t0,t1,x/sx),yy,rad);verts.push(p.x,p.y,p.z)}}for(let y=0;y<sy;y++)for(let x=0;x<sx;x++){let q=y*(sx+1)+x;idx.push(q,q+1,q+sx+1,q+1,q+sx+2,q+sx+1)}let g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(verts,3));g.setIndex(idx);g.computeVertexNormals();let mesh=new THREE.Mesh(g,mat(K().tile,.72));mesh.userData.tileId=id;mesh.renderOrder=2;tg.add(mesh);let og=new THREE.BufferGeometry();og.setAttribute('position',new THREE.Float32BufferAttribute(outline(t0,t1,y0,y1),3));let border=new THREE.LineLoop(og,new THREE.LineBasicMaterial({color:K().tileEdge}));border.renderOrder=5;tg.add(border);let th=(t0+t1)/2,y=(y0+y1)/2,n=new THREE.Vector3(Math.sin(th),0,Math.cos(th)),p=cyl(th,y,mugR(y)+.03),l=letter(board[id]||'',p,n,th);lg.add(l);tileMeshes.push(mesh);tiles.push({id,mesh,border,center:p,normal:n,theta:th,y})}
function buildTiles(){clear(tg);clear(lg);tiles=[];tileMeshes=[];adj=new Map();for(let r=0;r<R;r++)for(let c=0;c<C;c++){let id=r*C+c;adj.set(id,new Set());makeTile(r,c,id)}for(let r=0;r<R;r++)for(let c=0;c<C;c++){let id=r*C+c;for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){if(!dr&&!dc)continue;let rr=r+dr,cc=c+dc;if(rr>=0&&rr<R&&cc>=0&&cc<C)link(id,rr*C+cc)}}ui.tiles.textContent=tiles.length;ui.route.textContent='Front'}
function centerModel(){content.position.set(0,0,0);let box=new THREE.Box3().setFromObject(body);box.expandByObject(tg);content.position.copy(box.getCenter(new THREE.Vector3()).multiplyScalar(-1))}
function samples(a,b){let A=tiles[a],B=tiles[b],out=[],d=B.theta-A.theta;if(d>Math.PI)d-=Math.PI*2;if(d<-Math.PI)d+=Math.PI*2;for(let i=0;i<=14;i++){let t=i/14,th=A.theta+d*t,y=THREE.MathUtils.lerp(A.y,B.y,t),n=new THREE.Vector3(Math.sin(th),0,Math.cos(th));out.push({p:cyl(th,y,mugR(y)+.038),n})}return out}
function ribbon(ss,w,color,lift,order){let v=[],ix=[];for(let i=0;i<ss.length;i++){let s=ss[i],pr=ss[Math.max(0,i-1)].p,nx=ss[Math.min(ss.length-1,i+1)].p,t=nx.clone().sub(pr).normalize(),side=new THREE.Vector3().crossVectors(s.n,t).normalize(),p=s.p.clone().add(s.n.clone().multiplyScalar(lift)),h=w/2,L=p.clone().add(side.clone().multiplyScalar(h)),Rr=p.clone().add(side.clone().multiplyScalar(-h));v.push(L.x,L.y,L.z,Rr.x,Rr.y,Rr.z);if(i<ss.length-1){let a=i*2;ix.push(a,a+1,a+2,a+1,a+3,a+2)}}let g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(v,3));g.setIndex(ix);let m=new THREE.Mesh(g,new THREE.MeshBasicMaterial({color,side:THREE.DoubleSide,depthWrite:false}));m.renderOrder=order;return m}
function drawPath(p,col){for(let i=1;i<p.length;i++){let s=samples(p[i-1],p[i]);trails.add(ribbon(s,.20,K().under,.002,3),ribbon(s,.13,col,.004,4),ribbon(s,.07,col,.008,5))}}
function styles(){clear(trails);let c=K(),S=new Set(sel);for(let t of tiles){let color=c.tile,border=c.tileEdge,em=0;if((flash.get(t.id)||0)>performance.now()){color=border=c.bad;em=.18}else if(S.has(t.id)){color=border=c.sel;em=.12}else if(solved.has(t.id)){color=border=c.sol;em=.08}t.mesh.material.color.setHex(color);t.mesh.material.emissive.setHex(color);t.mesh.material.emissiveIntensity=em;t.border.material.color.setHex(border)}foundPaths.forEach(p=>drawPath(p,c.pathSol));if(sel.length>1)drawPath(sel,c.pathSel);render()}
function route(len,used){for(let st of shuffle([...Array(R*C).keys()].filter(i=>!used.has(i)))){let p=[st],seen=new Set(p),dfs=()=>{if(p.length===len)return true;for(let n of shuffle([...adj.get(p.at(-1))].filter(i=>!seen.has(i)&&!used.has(i)))){seen.add(n);p.push(n);if(dfs())return true;p.pop();seen.delete(n)}return false};if(dfs())return p}return null}
function puzzle(){if(!adj.size){for(let r=0;r<R;r++)for(let c=0;c<C;c++){let id=r*C+c;adj.set(id,new Set());for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){let rr=r+dr,cc=c+dc;if((dr||dc)&&rr>=0&&rr<R&&cc>=0&&cc<C)adj.get(id).add(rr*C+cc)}}}for(let a=0;a<120;a++){let used=new Set(),paths=new Map(),ok=true;for(let w of W){let p=route(w.length,used);if(!p){ok=false;break}p.forEach(i=>used.add(i));paths.set(w,p)}if(ok){board=Array(R*C).fill('').map(()=>POOL[rnd(POOL.length)]);paths.forEach((p,w)=>p.forEach((id,i)=>board[id]=w[i]));return}}throw Error('Could not build puzzle')}
function targetUI(){ui.targets.innerHTML='';for(let w of targets){let e=document.createElement('div');e.className='target-chip'+(found.has(w)?' found':'');e.innerHTML=`<strong>${w}</strong><span>${found.has(w)?'Found ✓':w.length+' letters'}</span>`;ui.targets.appendChild(e)}}
const word=()=>sel.map(i=>board[i]).join('');function update(){ui.word.textContent=word()||'Tap a tile to start';ui.meta.textContent=sel.length?(rot&&timerPaused?`Timer paused while rotating · ${(timerRemain/1000).toFixed(1)}s remaining`:`${sel.length} tile${sel.length===1?'':'s'} · Cube-style touching path · 8s timer`):'8 seconds after every tile · or press Check word';ui.clear.disabled=!sel.length;ui.check.disabled=sel.length<3;ui.found.textContent=`${found.size}/${targets.length}`;ui.score.textContent=score}
function toast(x){ui.toast.textContent=x;ui.toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>ui.toast.classList.remove('show'),1400)}function stopT(reset=true){clearInterval(timer);timer=null;timerPaused=false;timerRemain=MS;if(reset)ui.bar.style.width='0%'}function startT(ms=MS){clearInterval(timer);timerRemain=ms;timerStart=performance.now();timerPaused=false;timer=setInterval(()=>{let left=Math.max(0,timerRemain-(performance.now()-timerStart));ui.bar.style.width=left/MS*100+'%';if(!left){stopT(false);evaluate()}},50)}function pauseT(){if(!timer)return false;timerRemain=Math.max(1,timerRemain-(performance.now()-timerStart));clearInterval(timer);timer=null;timerPaused=true;return true}function resumeT(){if(sel.length&&timerPaused)startT(timerRemain)}
function evaluate(){if(!sel.length)return;stopT();let w=word(),p=[...sel];if(targets.includes(w)&&!found.has(w)){found.add(w);foundPaths.set(w,p);p.forEach(i=>solved.add(i));score+=w.length*120;toast(w+' found')}else{let id=sel.at(-1);flash.set(id,performance.now()+380);toast(targets.includes(w)?w+' already found':'Not a target word');setTimeout(()=>{flash.delete(id);styles()},400)}sel=[];targetUI();update();styles()}
function choose(id){let i=sel.indexOf(id);if(i>=0){sel=sel.slice(0,i);update();sel.length?startT():stopT();styles();return}let last=sel.at(-1);if(last!==undefined&&!adj.get(last).has(id)){flash.set(id,performance.now()+380);styles();setTimeout(()=>{flash.delete(id);styles()},400);return toast('Choose a touching tile')}sel.push(id);update();styles();let w=word();if(targets.includes(w)&&!found.has(w))setTimeout(()=>word()===w&&evaluate(),100);else startT()}
function fresh(){stopT();sel=[];found=new Set();foundPaths=new Map();solved=new Set();score=0;flash=new Map();puzzle();buildBody();buildTiles();centerModel();targetUI();update();rx=-.19;ry=-.28;startMs=Date.now();clearInterval(ticker);ticker=setInterval(()=>{let ms=Date.now()-startMs,m=Math.floor(ms/60000),s=Math.floor(ms%60000/1000),t=Math.floor(ms%1000/100);ui.time.textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${t}`},100);styles();toast(`New Word Mug prototype · v${V}`)}
function pick(x,y){let r=canvas.getBoundingClientRect();ptr.x=((x-r.left)/r.width)*2-1;ptr.y=-((y-r.top)/r.height)*2+1;ray.setFromCamera(ptr,camera);return ray.intersectObjects(tileMeshes,false)[0]?.object.userData.tileId??null}
canvas.addEventListener('pointerdown',e=>{let id=pick(e.clientX,e.clientY);if(id!==null)return choose(id);rot=true;pid=e.pointerId;lx=e.clientX;ly=e.clientY;timerPaused=pauseT();canvas.setPointerCapture?.(pid)});canvas.addEventListener('pointermove',e=>{if(!rot||e.pointerId!==pid)return;let dx=e.clientX-lx,dy=e.clientY-ly;lx=e.clientX;ly=e.clientY;ry+=dx*.0085;rx=clamp(rx+dy*.0085,-1.25,1.25);render()});function end(){if(!rot)return;rot=false;pid=null;let resume=timerPaused;timerPaused=false;update();if(resume)resumeT()}canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end);
ui.clear.onclick=()=>{sel=[];stopT();update();styles()};ui.check.onclick=evaluate;ui.newBtn.onclick=fresh;ui.next.onclick=fresh;ui.reset.onclick=()=>{rx=-.19;ry=-.28;render()};ui.theme.onclick=()=>{dark=!dark;document.documentElement.dataset.theme=dark?'dark':'light';ui.theme.textContent=dark?'Light mode':'Dark mode';buildBody();buildTiles();centerModel();styles()};function resize(){let r=stage.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/Math.max(1,r.height);camera.updateProjectionMatrix();render()}function render(){pivot.rotation.x=rx;pivot.rotation.y=ry;renderer.render(scene,camera)}new ResizeObserver(resize).observe(stage);fresh();resize();
})();
