(()=>{
'use strict';const s=window.WordShapeProto,ui=s.ui;
function route(len){for(const start of s.shuffle(s.nodes.map(n=>n.id)).slice(0,40)){const p=[start],seen=new Set([start]);const dfs=()=>{if(p.length===len)return true;for(const id of s.shuffle([...s.adj.get(p.at(-1))].filter(id=>!seen.has(id)))){seen.add(id);p.push(id);if(dfs())return true;p.pop();seen.delete(id)}return false};if(dfs())return p}return null}
function generate(){const paths=new Map();for(const word of s.cfg.words){const p=route(word.length);if(!p)throw new Error('Could not build prototype route');paths.set(word,p)}s.board=s.nodes.map(()=>s.POOL[s.rnd(s.POOL.length)]);paths.forEach((p,w)=>p.forEach((id,i)=>s.board[id]=w[i]));s.targets=[...s.cfg.words];s.targetPaths=paths}
function renderTargets(){ui.targets.innerHTML='';for(const w of s.targets){const e=document.createElement('div');e.className='target-chip'+(s.found.has(w)?' found':'');e.innerHTML=`<strong>${w}</strong><span>${s.found.has(w)?'Found ✓':w.length+' letters'}</span>`;ui.targets.appendChild(e)}}
const word=()=>s.selected.map(id=>s.board[id]).join('');
function updateUI(){ui.word.textContent=word()||'Tap a tile to start';ui.meta.textContent=s.selected.length?(s.rotating&&s.timerPaused?`Timer paused while rotating · ${(s.timerRemain/1000).toFixed(1)}s remaining`:`${s.selected.length} tile${s.selected.length===1?'':'s'} · touching path · 8s timer`):'8 seconds after every tile · or press Check word';ui.clear.disabled=!s.selected.length;ui.check.disabled=s.selected.length<3;ui.found.textContent=`${s.found.size}/${s.targets.length}`;ui.score.textContent=s.score}
function toast(text){ui.toast.textContent=text;ui.toast.classList.add('show');clearTimeout(s.toastTimer);s.toastTimer=setTimeout(()=>ui.toast.classList.remove('show'),1500)}function bad(id){s.flash.set(id,performance.now()+380);s.draw();setTimeout(()=>{s.flash.delete(id);s.draw()},400)}
function stopTimer(reset=true){clearInterval(s.timer);s.timer=null;s.timerStart=0;s.timerPaused=false;s.timerRemain=s.SEL;if(reset)ui.bar.style.width='0%'}function startTimer(ms=s.SEL){clearInterval(s.timer);s.timerRemain=ms;s.timerStart=performance.now();s.timerPaused=false;ui.bar.style.width=ms/s.SEL*100+'%';s.timer=setInterval(()=>{const left=Math.max(0,s.timerRemain-(performance.now()-s.timerStart));ui.bar.style.width=left/s.SEL*100+'%';if(left<=0){stopTimer(false);evaluate()}},50)}function pauseTimer(){if(!s.timer)return false;s.timerRemain=Math.max(1,s.timerRemain-(performance.now()-s.timerStart));clearInterval(s.timer);s.timer=null;s.timerStart=0;s.timerPaused=true;ui.bar.style.width=s.timerRemain/s.SEL*100+'%';return true}function resumeTimer(){if(s.selected.length&&s.timerPaused)startTimer(s.timerRemain)}
function evaluate(){if(!s.selected.length)return;stopTimer();const w=word(),p=[...s.selected];if(s.targets.includes(w)&&!s.found.has(w)){s.found.add(w);s.foundPaths.set(w,p);p.forEach(id=>s.solved.add(id));s.score+=w.length*120;toast(w+' found')}else{bad(s.selected.at(-1));toast(s.targets.includes(w)?w+' already found':'Not a target word')}s.selected=[];renderTargets();updateUI();s.draw();if(s.found.size===s.targets.length){const e=stopClock();ui.winText.textContent=`All ${s.targets.length} target words found in ${fmt(e)}.`;setTimeout(()=>ui.win.classList.add('show'),300)}}
function select(id){if(s.rotating)return;const i=s.selected.indexOf(id);if(i>=0){s.selected=s.selected.slice(0,i);updateUI();s.selected.length?startTimer():stopTimer();s.draw();return}const last=s.selected.at(-1);if(last!==undefined&&!s.adj.get(last).has(id)){bad(id);toast('Choose a touching tile');return}s.selected.push(id);updateUI();s.draw();const candidate=word();s.targets.includes(candidate)&&!s.found.has(candidate)?setTimeout(()=>word()===candidate&&evaluate(),120):startTimer()}
function fmt(ms){const m=Math.floor(ms/60000),sec=Math.floor(ms%60000/1000),t=Math.floor(ms%1000/100);return`${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}.${t}`}function clockUI(){ui.time.textContent=fmt(s.startMs?Date.now()-s.startMs:s.finalMs)}function startClock(){clearInterval(s.ticker);s.finalMs=0;s.startMs=Date.now();clockUI();s.ticker=setInterval(clockUI,100)}function stopClock(){if(s.startMs)s.finalMs=Date.now()-s.startMs;s.startMs=0;clearInterval(s.ticker);clockUI();return s.finalMs}
function reset(){s.rx=s.cfg.rx;s.ry=s.cfg.ry;s.draw()}function fresh(){stopTimer();stopClock();s.selected=[];s.found=new Set();s.foundPaths=new Map();s.solved=new Set();s.score=0;s.flash=new Map();ui.win.classList.remove('show');generate();renderTargets();updateUI();reset();startClock();toast(`New ${s.cfg.name} prototype · v${s.ver}`)}
function applyTheme(value){s.dark=value==='dark';document.documentElement.dataset.theme=s.dark?'dark':'light';ui.theme.textContent=s.dark?'Light mode':'Dark mode';ui.metaColor?.setAttribute('content',s.dark?'#091311':'#f3f7f4');try{localStorage.setItem('anitasPrototypeTheme',s.dark?'dark':'light')}catch(_){}s.draw()}
s.canvas.addEventListener('pointerdown',e=>{if(e.button!==undefined&&e.button!==0)return;const id=s.hit(e.clientX,e.clientY);if(id!==null){select(id);return}s.rotating=true;s.pid=e.pointerId;s.lx=e.clientX;s.ly=e.clientY;s.timerPaused=pauseTimer();updateUI();try{s.canvas.setPointerCapture(e.pointerId)}catch(_){}s.stage.classList.add('rotating')});s.canvas.addEventListener('pointermove',e=>{if(!s.rotating||e.pointerId!==s.pid)return;const dx=e.clientX-s.lx,dy=e.clientY-s.ly;s.lx=e.clientX;s.ly=e.clientY;s.ry=s.normAng(s.ry+dx*.34);s.rx=s.normAng(s.rx-dy*.34);s.draw()});function end(e){if(!s.rotating)return;if(e&&e.pointerId!==undefined&&s.pid!==null&&e.pointerId!==s.pid)return;s.rotating=false;s.pid=null;s.stage.classList.remove('rotating');const resume=s.timerPaused;s.timerPaused=false;updateUI();if(resume)resumeTimer()}s.canvas.addEventListener('pointerup',end);s.canvas.addEventListener('pointercancel',end);s.canvas.addEventListener('lostpointercapture',()=>end());window.addEventListener('blur',()=>end());
ui.clear.addEventListener('click',()=>{s.selected=[];stopTimer();updateUI();s.draw()});ui.check.addEventListener('click',evaluate);ui.newBtn.addEventListener('click',fresh);ui.next.addEventListener('click',fresh);ui.reset.addEventListener('click',reset);ui.theme.addEventListener('click',()=>applyTheme(s.dark?'light':'dark'));document.addEventListener('keydown',e=>{if(e.key==='Escape'){s.selected=[];stopTimer();updateUI();s.draw()}if(e.key==='Enter'&&s.selected.length>=3)evaluate()});
function resize(){const r=s.stage.getBoundingClientRect();s.dpr=Math.min(window.devicePixelRatio||1,2);s.w=Math.max(1,r.width);s.h=Math.max(1,r.height);s.canvas.width=Math.round(s.w*s.dpr);s.canvas.height=Math.round(s.h*s.dpr);s.canvas.style.width=s.w+'px';s.canvas.style.height=s.h+'px';s.ctx.setTransform(s.dpr,0,0,s.dpr,0,0);s.draw()}if('ResizeObserver'in window)new ResizeObserver(resize).observe(s.stage);else window.addEventListener('resize',resize);
s.build();let saved='light';try{saved=localStorage.getItem('anitasPrototypeTheme')||'light'}catch(_){}applyTheme(saved);fresh();resize();
})();
