(()=>{
'use strict';
const CFG={easy:{n:5,t:[7,9],l:'Easy'},medium:{n:7,t:[11,14],l:'Medium'},hard:{n:9,t:[16,20],l:'Hard'},expert:{n:10,t:[20,24],l:'Expert'}};
const COLORS=['#a9e8d1','#d9ccff','#e6a2df','#b8d9ff','#dfc9b7','#f4d58a','#9ed9e8','#c6e6a6','#f4b8b8','#b9b4ee','#add9c8','#e7bfe8','#c2d5ff','#ffd0ad','#b7e7d8','#e5c8ff','#f2c1d0','#d2e7a8','#b8d8e6','#e9d6a5','#cfc3f3','#b5e0bf','#efc5ae','#bad7f0'];
const $=id=>document.getElementById(id),board=$('board'),timer=$('timer'),status=$('status'),diff=$('difficulty'),modal=$('modal'),mTitle=$('modalTitle'),mBody=$('modalBody'),mCancel=$('modalCancel'),mGo=$('modalGo');
let N=7,clues=[],solution=[],placed=[],history=[],cells=[],start=null,last=null,started=0,tick=null,done=false,token=0;
const ri=(a,b)=>a+Math.floor(Math.random()*(b-a+1)),key=(r,c)=>r*N+c,inside=(q,r,c)=>r>=q.r1&&r<=q.r2&&c>=q.c1&&c<=q.c2,area=q=>(q.r2-q.r1+1)*(q.c2-q.c1+1),eq=(a,b)=>a&&b&&a.r1===b.r1&&a.r2===b.r2&&a.c1===b.c1&&a.c2===b.c2,over=(a,b)=>!(a.r2<b.r1||a.r1>b.r2||a.c2<b.c1||a.c1>b.c2);
function partition(n,target){let a=[{r1:0,c1:0,r2:n-1,c2:n-1}],g=0;while(a.length<target&&g++<2000){const cand=a.map((r,i)=>({r,i,s:area(r)})).filter(x=>x.r.r2>x.r.r1||x.r.c2>x.r.c1).sort((x,y)=>y.s-x.s);if(!cand.length)break;const p=cand[Math.floor(Math.random()*Math.min(cand.length,Math.max(2,Math.ceil(cand.length*.45))))],r=p.r,h=r.r2-r.r1+1,w=r.c2-r.c1+1,o=[];for(let c=1;c<h;c++){const x=c*w,y=(h-c)*w;if(x>=2&&y>=2)o.push({d:0,c,s:Math.abs(x-y)+Math.random()*4})}for(let c=1;c<w;c++){const x=c*h,y=(w-c)*h;if(x>=2&&y>=2)o.push({d:1,c,s:Math.abs(x-y)+Math.random()*4})}if(!o.length)continue;o.sort((x,y)=>x.s-y.s);const z=o[Math.floor(Math.random()*Math.min(3,o.length))];let x,y;if(!z.d){x={r1:r.r1,c1:r.c1,r2:r.r1+z.c-1,c2:r.c2};y={r1:r.r1+z.c,c1:r.c1,r2:r.r2,c2:r.c2}}else{x={r1:r.r1,c1:r.c1,r2:r.r2,c2:r.c1+z.c-1};y={r1:r.r1,c1:r.c1+z.c,r2:r.r2,c2:r.c2}}a.splice(p.i,1,x,y)}return a}
function mkClues(rs){return rs.map((r,id)=>{const a=[];for(let y=r.r1;y<=r.r2;y++)for(let x=r.c1;x<=r.c2;x++)a.push([y,x]);const [row,col]=a[ri(0,a.length-1)];return{row,col,value:area(r),id}})}
function candidates(c,all){const out=[],v=c.value;for(let h=1;h<=N;h++){if(v%h)continue;const w=v/h;if(w>N)continue;for(let r=Math.max(0,c.row-h+1);r<=Math.min(c.row,N-h);r++)for(let x=Math.max(0,c.col-w+1);x<=Math.min(c.col,N-w);x++){const q={r1:r,c1:x,r2:r+h-1,c2:x+w-1};let n=0;for(const z of all){if(inside(q,z.row,z.col))n++;if(n>1)break}if(n===1)out.push(q)}}return out}
function solve(all,limit=2){const opts=all.map(c=>candidates(c,all));if(opts.some(x=>!x.length))return{count:0,one:null};const used=new Uint8Array(N*N),chosen=new Array(all.length);let count=0,one=null;const fits=q=>{for(let r=q.r1;r<=q.r2;r++)for(let c=q.c1;c<=q.c2;c++)if(used[key(r,c)])return false;return true},paint=(q,v)=>{for(let r=q.r1;r<=q.r2;r++)for(let c=q.c1;c<=q.c2;c++)used[key(r,c)]=v};function dfs(depth){if(count>=limit)return;if(depth===all.length){count++;if(!one)one=chosen.map(x=>({...x}));return}let bi=-1,bl=null;for(let i=0;i<all.length;i++){if(chosen[i])continue;const v=opts[i].filter(fits);if(!v.length)return;if(bl===null||v.length<bl.length){bi=i;bl=v;if(v.length===1)break}}for(const q of bl){chosen[bi]=q;paint(q,1);dfs(depth+1);paint(q,0);chosen[bi]=null;if(count>=limit)return}}dfs(0);return{count,one}}
async function generate(){const id=++token,cfg=CFG[diff.value];N=cfg.n;done=false;placed=[];history=[];clues=[];solution=[];stopTimer();timer.textContent='00:00';status.textContent='Erstelle und prüfe ein lösbares Level …';board.innerHTML='';await new Promise(r=>setTimeout(r,20));let hit=null,max=diff.value==='expert'?600:350;for(let a=0;a<max;a++){if(id!==token)return;const target=ri(cfg.t[0],cfg.t[1]),p=partition(N,target);if(p.length<Math.floor(target*.9))continue;const cs=mkClues(p),s=solve(cs);if(s.count===1){hit={cs,sol:s.one};break}if(a%20===0)await new Promise(r=>setTimeout(r,0))}for(let round=0;!hit&&round<20;round++){for(let a=0;a<100;a++){const p=partition(N,ri(cfg.t[0],cfg.t[1])),cs=mkClues(p),s=solve(cs);if(s.count===1){hit={cs,sol:s.one};break}}await new Promise(r=>setTimeout(r,0))}if(!hit){status.textContent='Generator startet neu …';setTimeout(generate,50);return}clues=hit.cs;solution=hit.sol;render();startTimer();status.textContent=`${cfg.l} · eindeutige Lösung geprüft ✓`}
function render(){board.style.gridTemplateColumns=`repeat(${N},1fr)`;board.style.gridTemplateRows=`repeat(${N},1fr)`;cells=[];const map=new Map(clues.map(c=>[key(c.row,c.col),c]));for(let r=0;r<N;r++)for(let c=0;c<N;c++){const e=document.createElement('div');e.className='cell'+(((r+c)&1)?' alt':'');e.dataset.r=r;e.dataset.c=c;const q=map.get(key(r,c));if(q){const s=document.createElement('span');s.className='num';s.textContent=q.value;e.appendChild(s)}board.appendChild(e);cells.push(e)}recolor()}
const cell=(r,c)=>cells[key(r,c)],norm=(a,b)=>({r1:Math.min(a.r,b.r),r2:Math.max(a.r,b.r),c1:Math.min(a.c,b.c),c2:Math.max(a.c,b.c)});
function at(x,y){const e=document.elementFromPoint(x,y)?.closest?.('.cell');return e&&board.contains(e)?{r:+e.dataset.r,c:+e.dataset.c}:null}
function preview(q){cells.forEach(e=>e.classList.remove('preview'));if(!q)return;for(let r=q.r1;r<=q.r2;r++)for(let c=q.c1;c<=q.c2;c++)cell(r,c).classList.add('preview')}
function valid(q){const inC=clues.filter(c=>inside(q,c.row,c.col));if(inC.length!==1)return{ok:false,msg:'Ein Rechteck muss genau eine Zahl enthalten.'};if(area(q)!==inC[0].value)return{ok:false,msg:`Fläche ${area(q)} passt nicht zur Zahl ${inC[0].value}.`};return{ok:true,clue:inC[0]}}
function flash(q){for(let r=q.r1;r<=q.r2;r++)for(let c=q.c1;c<=q.c2;c++){const e=cell(r,c);e.classList.add('bad');setTimeout(()=>e.classList.remove('bad'),280)}}
function put(q){const v=valid(q);if(!v.ok){status.textContent=v.msg;flash(q);return}const ex=placed.findIndex(p=>inside(p,v.clue.row,v.clue.col));if(placed.some((p,i)=>i!==ex&&over(p,q))){status.textContent='Dieses Rechteck überlappt ein bestehendes.';flash(q);return}history.push(placed.map(x=>({...x})));const x={...q,clueId:v.clue.id};ex>=0?placed[ex]=x:placed.push(x);recolor();status.textContent='Passt geometrisch. Weiter!';win()}
function recolor(){cells.forEach(e=>{e.style.background='';e.style.borderRadius='8px'});placed.forEach(p=>{const col=COLORS[p.clueId%COLORS.length];for(let r=p.r1;r<=p.r2;r++)for(let c=p.c1;c<=p.c2;c++){const e=cell(r,c);e.style.background=col;const d=8;e.style.borderRadius=`${r===p.r1&&c===p.c1?d:3}px ${r===p.r1&&c===p.c2?d:3}px ${r===p.r2&&c===p.c2?d:3}px ${r===p.r2&&c===p.c1?d:3}px`}})}
function win(){if(placed.length!==clues.length)return false;if(placed.reduce((s,p)=>s+area(p),0)!==N*N)return false;for(const c of clues){const p=placed.find(x=>x.clueId===c.id);if(!p||!eq(p,solution[c.id]))return false}done=true;stopTimer();status.textContent='Gelöst! 🎉';showModal('Geschafft!',`<p>Du hast das ${CFG[diff.value].l}-Level in <strong>${timer.textContent}</strong> gelöst.</p><p>Das Level wurde vor dem Start auf eine eindeutige Lösung geprüft.</p>`,true);return true}
function check(){if(done)return;let n=0;for(const p of placed)if(!eq(p,solution[p.clueId])){n++;flash(p)}status.textContent=n?`${n} Rechteck${n===1?'':'e'} stimmt${n===1?'':'en'} noch nicht.`:(placed.length===clues.length?'Alles korrekt.':'Bisher alles korrekt ✓');if(!n)win()}
function hint(){if(done)return;const m=clues.filter(c=>{const p=placed.find(x=>x.clueId===c.id);return!p||!eq(p,solution[c.id])});if(!m.length)return;const c=m[ri(0,m.length-1)],q=solution[c.id];history.push(placed.map(x=>({...x})));placed=placed.filter(p=>p.clueId===c.id||!over(p,q));const i=placed.findIndex(p=>p.clueId===c.id),x={...q,clueId:c.id};i>=0?placed[i]=x:placed.push(x);recolor();status.textContent=`Hinweis: Rechteck mit ${c.value} wurde eingesetzt.`;win()}
function erase(p){const i=placed.findIndex(q=>inside(q,p.r,p.c));if(i<0)return;history.push(placed.map(x=>({...x})));placed.splice(i,1);recolor();status.textContent='Rechteck gelöscht.'}
function undo(){if(!history.length)return;placed=history.pop();recolor();status.textContent='Rückgängig.'}
function reveal(){if(done)return;placed=solution.map((q,i)=>({...q,clueId:i}));recolor();done=true;stopTimer();status.textContent='Lösung angezeigt.'}
function startTimer(){started=performance.now();tick=setInterval(()=>{const s=Math.floor((performance.now()-started)/1000);timer.textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')},250)}function stopTimer(){if(tick){clearInterval(tick);tick=null}}
function showModal(t,b,newBtn){mTitle.textContent=t;mBody.innerHTML=b;mGo.style.display=newBtn?'block':'none';modal.classList.add('show')}function hide(){modal.classList.remove('show')}
board.addEventListener('pointerdown',e=>{if(done)return;const p=at(e.clientX,e.clientY);if(!p)return;start=last=p;board.setPointerCapture?.(e.pointerId);preview(norm(start,last));e.preventDefault()});board.addEventListener('pointermove',e=>{if(!start)return;const p=at(e.clientX,e.clientY);if(p){last=p;preview(norm(start,last))}e.preventDefault()});board.addEventListener('pointerup',e=>{if(!start)return;const p=at(e.clientX,e.clientY)||last,q=norm(start,p);start=last=null;preview(null);put(q);e.preventDefault()});board.addEventListener('pointercancel',()=>{start=last=null;preview(null)});
$('eraseBtn').addEventListener('click',()=>{status.textContent='Tippe auf ein farbiges Rechteck, das du löschen möchtest.';const once=e=>{const p=at(e.clientX,e.clientY);if(p)erase(p);board.removeEventListener('pointerdown',once,true);e.stopPropagation();e.preventDefault()};board.addEventListener('pointerdown',once,true)});$('undoBtn').addEventListener('click',undo);$('hintBtn').addEventListener('click',hint);$('checkBtn').addEventListener('click',check);$('newBtn').addEventListener('click',generate);diff.addEventListener('change',generate);
$('rulesBtn').addEventListener('click',()=>showModal('So funktioniert Shikaku','<p>Teile das gesamte Feld in Rechtecke auf.</p><p>Jedes Rechteck muss <strong>genau eine Zahl</strong> enthalten. Die Zahl ist die <strong>Fläche</strong> des Rechtecks.</p><p>Ziehe vom ersten bis zum letzten Feld. Überlappungen sind nicht erlaubt.</p>',false));$('solveBtn').addEventListener('click',()=>{showModal('Lösung anzeigen?','<p>Damit wird das aktuelle Level beendet und die vollständige Lösung eingeblendet.</p>',false);mCancel.textContent='Abbrechen';mCancel.onclick=()=>{hide();mCancel.textContent='Schliessen';mCancel.onclick=null};mGo.style.display='block';mGo.textContent='Lösung zeigen';mGo.onclick=()=>{hide();reveal();mGo.textContent='Neues Level';mGo.onclick=null}});mCancel.addEventListener('click',hide);mGo.addEventListener('click',()=>{hide();generate()});modal.addEventListener('click',e=>{if(e.target===modal)hide()});
generate();
})();